name: Deployment 2
on: [push]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Linting
              run: npm run lint
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install dependecies
              run: npm ci
            - name: test code
              run: npm run test
    deployment2:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install dependecies
              run: npm ci
            - name: build code
              run: npm run build
            - name: Deploy
              run: echo "Deploying Code....."